//////////Техника Сотрудников//////////
###
GET http://localhost:8080/employee_equipments

###
GET http://localhost:8080/employee_equipments/28

###
POST http://localhost:8080/employee_equipments
Content-Type: application/json

{
    "employees_id": 3,
    "technique_id": 10
}

###
PUT http://localhost:8080/employee_equipments/4
Content-Type: application/json

{
    "employees_id": 6,
    "technique_id": 4
}

###
DELETE http://localhost:8080/employee_equipments/24

###
GET http://localhost:8080/employee_equipments?&technique_id=9&employees_id&page=1&limit=2
Content-Type: application/json