//////////Техника//////////
###
GET http://localhost:8080/techniques

###
GET http://localhost:8080/techniques/3

###
POST http://localhost:8080/techniques
Content-Type: application/json

{
    "name": "Apple",
    "type_id": 48
}
//"archived": false,
// "deleted": false

###
PUT http://localhost:8080/techniques/3
Content-Type: application/json

{
     "name": "Huawei",
    "type_id": 4
}

###
DELETE http://localhost:8080/techniques/9

###
GET http://localhost:8080/techniques?&name=Apple&type_id=8&page=1&limit=2
Content-Type: application/json